### ISSUE TITLE
How to use this library with co-log?

### ISSUE THREAD

**Issue by srid** [kowainik/unlift#5]
I noticed that co-log has no `askLogAction` that I can use to pull out the logger configuration before dropping to IO in functions like `withCurrentDirectory` and then re-invoking `usingLoggerT logAction` to get into the logger monad. 

Is unlift the right approach to handle this problem? If so it would be good to have an example in the README.

**Comment by chshersh** [comment]
@srid I'm not quite sure that I understand your question. Maybe you can provide an example of code that you have a problem with? I will write some of my thoughts meanwhile.

The [recommended approach](https://github.com/kowainik/co-log/blob/main/co-log/tutorials/2-custom/Custom.md) of using `co-log` in applications is to introduce an environment, parametrised by a monad:

```haskell
data Env (m :: Type -> Type) = Env
    { envLogAction :: LogAction m MyMessage
    , envPort :: Int
    }
```

And then use it inside the `ReaderT` monad:

```haskell
newtype App a = App
    { unApp :: ReaderT (Env App) IO a
    } deriving newtype (Functor, Applicative, Monad, MonadIO, MonadReader (Env App), MonadUnlift IO)
```

You can then use the `asks` function to get `LogAction` and, indeed, you can use the `withRunInBase` function to run the logger inside the `IO` monad:

```haskell
foo :: App ()
foo = do
    LogAction log <- asks envLogAction
    withRunInBase $ \runInBase -> withCurrentDirectory "/some/path" $ do
        runInBase $ log "Running from directory: /some/path"
        ... ordinary actions in the IO monad ...
        runInBase $ log "Finishing actions in the directory: /some/path"
```

Does this help with your question?

An example of using `co-log` with `MonadUnlift` would be nice, but I think it should be in the `co-log` repository (probably as a separate tutorial). A tutorial on `MonadUnlift` alone would be nice as well, and we do have plans to write a more detailed tutorial with examples on the subject.
